// Package analytics provides zone and line crossing detection for tracked objects.
// It processes track data from the ByteTrack tracker to generate events like
// zone enter/exit, line crossing, and dwell detection.
package analytics

import (
	"math"
	"sync"
	"time"

	"github.com/ailakshya/infergo/tracker"
)

// Point represents a 2D coordinate.
type Point struct {
	X float64 `json:"x" yaml:"x"`
	Y float64 `json:"y" yaml:"y"`
}

// Zone defines a region or line in the frame for crossing/occupancy analysis.
type Zone struct {
	Name    string  `json:"name" yaml:"name"`
	Polygon []Point `json:"polygon,omitempty" yaml:"polygon,omitempty"`
	Type    string  `json:"type" yaml:"type"` // "zone" or "line"
	// For lines:
	P1  Point  `json:"p1,omitempty" yaml:"p1,omitempty"`
	P2  Point  `json:"p2,omitempty" yaml:"p2,omitempty"`
	Dir string `json:"direction,omitempty" yaml:"direction,omitempty"` // "both", "in", "out"

	// Pre-computed bounding box for fast rejection (set by ZoneManager).
	bbMinX, bbMinY, bbMaxX, bbMaxY float64
}

// ZoneEvent represents an analytics event generated by zone/line crossing detection.
type ZoneEvent struct {
	Type      string        `json:"type"`       // "enter", "exit", "cross", "dwell"
	ZoneName  string        `json:"zone_name"`
	TrackID   int           `json:"track_id"`
	ClassID   int           `json:"class_id"`
	Timestamp time.Time     `json:"timestamp"`
	Duration  time.Duration `json:"duration,omitempty"`  // for dwell events
	Direction string        `json:"direction,omitempty"` // for line crossing: "in" or "out"
}

// trackZoneState holds the per-track state within a specific zone.
type trackZoneState struct {
	enterTime time.Time
	lastSeen  time.Time
	// For line crossing: the signed side of the line the track was on last frame.
	lastSide float64
}

// ZoneManager processes tracked objects against defined zones and generates events.
type ZoneManager struct {
	zones []Zone

	mu         sync.Mutex
	trackZones map[int]map[string]*trackZoneState // trackID -> zoneName -> state
	// Track last known center positions for line crossing.
	trackPos map[int]Point // trackID -> last center point
}

// NewZoneManager creates a new ZoneManager with the given zones.
// It pre-computes bounding boxes for polygon zones for fast rejection.
func NewZoneManager(zones []Zone) *ZoneManager {
	// Pre-compute bounding boxes.
	for i := range zones {
		z := &zones[i]
		if z.Type == "zone" && len(z.Polygon) > 0 {
			z.bbMinX = math.Inf(1)
			z.bbMinY = math.Inf(1)
			z.bbMaxX = math.Inf(-1)
			z.bbMaxY = math.Inf(-1)
			for _, p := range z.Polygon {
				if p.X < z.bbMinX {
					z.bbMinX = p.X
				}
				if p.Y < z.bbMinY {
					z.bbMinY = p.Y
				}
				if p.X > z.bbMaxX {
					z.bbMaxX = p.X
				}
				if p.Y > z.bbMaxY {
					z.bbMaxY = p.Y
				}
			}
		} else if z.Type == "line" {
			z.bbMinX = math.Min(z.P1.X, z.P2.X)
			z.bbMinY = math.Min(z.P1.Y, z.P2.Y)
			z.bbMaxX = math.Max(z.P1.X, z.P2.X)
			z.bbMaxY = math.Max(z.P1.Y, z.P2.Y)
		}
	}

	return &ZoneManager{
		zones:      zones,
		trackZones: make(map[int]map[string]*trackZoneState),
		trackPos:   make(map[int]Point),
	}
}

// TrackedObject is a minimal interface for a tracked detection.
// It matches the fields available from tracker.Track.
type TrackedObject struct {
	ID    int
	Class int
	Box   [4]float64 // x1, y1, x2, y2
}

// TrackedObjectFromTrack converts a tracker.Track to a TrackedObject.
func TrackedObjectFromTrack(t tracker.Track) TrackedObject {
	return TrackedObject{
		ID:    t.ID,
		Class: t.Class,
		Box:   t.Box,
	}
}

// Update processes the current frame's tracked objects and returns any zone events.
// Call this once per frame with all active tracks.
func (zm *ZoneManager) Update(tracks []TrackedObject, timestamp time.Time) []ZoneEvent {
	zm.mu.Lock()
	defer zm.mu.Unlock()

	var events []ZoneEvent

	// Build a set of active track IDs this frame.
	activeIDs := make(map[int]bool, len(tracks))

	for _, t := range tracks {
		activeIDs[t.ID] = true
		center := boxCenter(t.Box)

		// Ensure per-track zone map exists.
		if zm.trackZones[t.ID] == nil {
			zm.trackZones[t.ID] = make(map[string]*trackZoneState)
		}

		prevPos, hasPrev := zm.trackPos[t.ID]

		for i := range zm.zones {
			z := &zm.zones[i]

			switch z.Type {
			case "zone":
				inZone := pointInPolygon(center, z)
				state, wasIn := zm.trackZones[t.ID][z.Name]

				if inZone && !wasIn {
					// Enter event.
					zm.trackZones[t.ID][z.Name] = &trackZoneState{
						enterTime: timestamp,
						lastSeen:  timestamp,
					}
					events = append(events, ZoneEvent{
						Type:      "enter",
						ZoneName:  z.Name,
						TrackID:   t.ID,
						ClassID:   t.Class,
						Timestamp: timestamp,
					})
				} else if inZone && wasIn {
					// Still in zone: update lastSeen, check for dwell.
					state.lastSeen = timestamp
				} else if !inZone && wasIn {
					// Exit event.
					dur := timestamp.Sub(state.enterTime)
					events = append(events, ZoneEvent{
						Type:      "exit",
						ZoneName:  z.Name,
						TrackID:   t.ID,
						ClassID:   t.Class,
						Timestamp: timestamp,
						Duration:  dur,
					})
					delete(zm.trackZones[t.ID], z.Name)
				}

			case "line":
				if !hasPrev {
					break
				}
				// Line crossing detection using signed area.
				curSide := lineSide(z.P1, z.P2, center)
				prevSideLine := lineSide(z.P1, z.P2, prevPos)

				// Check if track crossed the line (sign change, neither zero).
				if prevSideLine != 0 && curSide != 0 && prevSideLine*curSide < 0 {
					// Determine direction: positive to negative = "out", negative to positive = "in".
					dir := "in"
					if prevSideLine > 0 && curSide < 0 {
						dir = "out"
					}

					if z.Dir == "both" || z.Dir == dir || z.Dir == "" {
						events = append(events, ZoneEvent{
							Type:      "cross",
							ZoneName:  z.Name,
							TrackID:   t.ID,
							ClassID:   t.Class,
							Timestamp: timestamp,
							Direction: dir,
						})
					}
				}
			}
		}

		zm.trackPos[t.ID] = center
	}

	// Generate exit events for tracks that disappeared while in zones.
	for trackID, zones := range zm.trackZones {
		if activeIDs[trackID] {
			continue
		}
		for zoneName, state := range zones {
			dur := timestamp.Sub(state.enterTime)
			events = append(events, ZoneEvent{
				Type:      "exit",
				ZoneName:  zoneName,
				TrackID:   trackID,
				ClassID:   -1, // unknown since track is gone
				Timestamp: timestamp,
				Duration:  dur,
			})
		}
		delete(zm.trackZones, trackID)
		delete(zm.trackPos, trackID)
	}

	return events
}

// DwellEvents checks all tracks currently in zones and returns dwell events
// for any that have been present longer than the given threshold.
func (zm *ZoneManager) DwellEvents(timestamp time.Time, threshold time.Duration) []ZoneEvent {
	zm.mu.Lock()
	defer zm.mu.Unlock()

	var events []ZoneEvent
	for trackID, zones := range zm.trackZones {
		for zoneName, state := range zones {
			dur := timestamp.Sub(state.enterTime)
			if dur >= threshold {
				events = append(events, ZoneEvent{
					Type:      "dwell",
					ZoneName:  zoneName,
					TrackID:   trackID,
					ClassID:   -1,
					Timestamp: timestamp,
					Duration:  dur,
				})
			}
		}
	}
	return events
}

// Occupancy returns the number of tracks currently inside the named zone.
func (zm *ZoneManager) Occupancy(zoneName string) int {
	zm.mu.Lock()
	defer zm.mu.Unlock()

	count := 0
	for _, zones := range zm.trackZones {
		if _, ok := zones[zoneName]; ok {
			count++
		}
	}
	return count
}

// ActiveTrackCount returns the total number of tracks being monitored.
func (zm *ZoneManager) ActiveTrackCount() int {
	zm.mu.Lock()
	defer zm.mu.Unlock()
	return len(zm.trackZones)
}

// --- Geometry helpers ---

// boxCenter returns the center point of a bounding box [x1, y1, x2, y2].
func boxCenter(box [4]float64) Point {
	return Point{
		X: (box[0] + box[2]) / 2,
		Y: (box[1] + box[3]) / 2,
	}
}

// pointInPolygon tests if a point is inside a polygon zone using the ray casting
// algorithm. It first checks the pre-computed bounding box for fast rejection.
func pointInPolygon(p Point, z *Zone) bool {
	// Fast bounding box rejection.
	if p.X < z.bbMinX || p.X > z.bbMaxX || p.Y < z.bbMinY || p.Y > z.bbMaxY {
		return false
	}

	n := len(z.Polygon)
	if n < 3 {
		return false
	}

	inside := false
	j := n - 1
	for i := 0; i < n; i++ {
		pi := z.Polygon[i]
		pj := z.Polygon[j]

		if (pi.Y > p.Y) != (pj.Y > p.Y) &&
			p.X < (pj.X-pi.X)*(p.Y-pi.Y)/(pj.Y-pi.Y)+pi.X {
			inside = !inside
		}
		j = i
	}
	return inside
}

// lineSide returns the signed value indicating which side of the line (P1->P2) the
// point is on. Positive = left, negative = right, zero = on the line.
// Uses the cross product of (P2-P1) x (P-P1).
func lineSide(p1, p2, p Point) float64 {
	return (p2.X-p1.X)*(p.Y-p1.Y) - (p2.Y-p1.Y)*(p.X-p1.X)
}

// segmentsIntersect tests if line segment AB intersects line segment CD.
// Used for more precise line crossing detection when needed.
func segmentsIntersect(a, b, c, d Point) bool {
	d1 := lineSide(c, d, a)
	d2 := lineSide(c, d, b)
	d3 := lineSide(a, b, c)
	d4 := lineSide(a, b, d)

	if ((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) &&
		((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0)) {
		return true
	}

	// Collinear cases.
	if d1 == 0 && onSegment(c, d, a) {
		return true
	}
	if d2 == 0 && onSegment(c, d, b) {
		return true
	}
	if d3 == 0 && onSegment(a, b, c) {
		return true
	}
	if d4 == 0 && onSegment(a, b, d) {
		return true
	}
	return false
}

// onSegment checks if point p lies on segment (a, b), assuming p is collinear with a and b.
func onSegment(a, b, p Point) bool {
	return p.X >= math.Min(a.X, b.X) && p.X <= math.Max(a.X, b.X) &&
		p.Y >= math.Min(a.Y, b.Y) && p.Y <= math.Max(a.Y, b.Y)
}
